branch-defaults:
  default:
    environment: accessTechBackendEnvironment
    group_suffix: null
environment-defaults:
  Accesstech-env-1:
    branch: null
    repository: null
global:
  application_name: accessTechBackend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
