name: Manual CI/CD Pipeline

on:
  #push:
    #branches:
     # - development
  #pull_request:
    #branches:
      # - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install AWS Elastic Beanstalk CLI
      run: pip install awsebcli --upgrade

    - name: Set up AWS CLI
      run: choco install awscli

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1
        
  
    - name: Setup Python Virtual Environment and Initialize Elastic Beanstalk
      run: |
        cd backend/aws_deploy/inner
        eb init accesstech


    - name: Deploy Backend
      run: 
        .\deploy_Backend.bat

    - name: Deploy Ordering Frontend
      run:
        .\deploy_OrderingFrontend.bat
